# Generated by Django 2.2.2 on 2019-06-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='comment',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
